VISIT_QUERY = "SELECT URLS.URL, URLS.VISIT_COUNT FROM URLS, VISITS WHERE URLS.ID = VISITS.URL" \
    " ORDER BY URLS.VISIT_COUNT DESC;"

SEARCH_TERMS_QUERY = "SELECT KEYWORD_SEARCH_TERMS.LOWER_TERM FROM KEYWORD_SEARCH_TERMS;"

RECENT_SEARCH_TERMS_QUERY = "SELECT KEYWORD_SEARCH_TERMS.LOWER_TERM " \
    "FROM URLS, KEYWORD_SEARCH_TERMS WHERE (URLS.ID = KEYWORD_SEARCH_TERMS.URL_ID AND " \
    "URLS.LAST_VISIT_TIME > ?) ORDER BY URLS.LAST_VISIT_TIME DESC;"

URL_QUERY = "SELECT URLS.URL FROM URLS WHERE (URLS.URL NOT LIKE '%127.0.0.1%') AND (URLS.URL NOT LIKE '%localhost%') AND (URLS.URL LIKE 'http%');"

URL_INTERVAL_QUERY = "SELECT URLS.URL FROM URLS WHERE (URLS.LAST_VISIT_TIME > ? " \
                     "AND URLS.LAST_VISIT_TIME < ? AND URLS.URL LIKE 'http%' " \
                     "AND URLS.URL NOT LIKE '%127.0.0.1%' " \
                     "AND URLS.URL NOT LIKE '%localhost%');"
